add hash for exponential double values.
iden3/js-jsonld-merklization pull request #12
Opened 2023-03-23 15:18 UTC by vmidyllic

2023-03-23 17:30 UTC, Kolezhniuk requested changes

2023-03-24 13:16 UTC, vmidyllic commented on src/lib/utils.ts
> +    // this is for v2
why. it's for v2

2023-03-24 13:18 UTC, vmidyllic commented on src/lib/types/types.ts
> +export const isDouble = (v: number) => String(v).indexOf('.') !== -1 || Math.abs(v) >= 1e21;
see nothing wrong with indexof

2023-03-24 13:52 UTC, Kolezhniuk requested changes

2023-03-24 13:52 UTC, Kolezhniuk commented on src/lib/utils.ts
> +export const convertAnyToString = (v: unknown, datatype:string): string => {
but in this case, you're checking `typeof v` two times, why do we need that if we can check it once

2023-03-24 13:53 UTC, Kolezhniuk commented on src/lib/utils.ts
> +    // this is for v2
than it's better to mark this comment with TODO

2023-03-24 14:43 UTC, Kolezhniuk approved these changes

2023-03-24 15:57 UTC, merged